// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: stock.proto

package stock_client

import (
	"context"

	"bookNew/service/stock/rpc/stock"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductReply = stock.DeductReply
	DeductReq   = stock.DeductReq

	Stock interface {
		// 扣减库存 (Action)
		Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductReply, error)
		// 补偿库存 (Compensate) - 如果后续步骤失败，把库存加回来
		DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductReply, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

// 扣减库存 (Action)
func (m *defaultStock) Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductReply, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.Deduct(ctx, in, opts...)
}

// 补偿库存 (Compensate) - 如果后续步骤失败，把库存加回来
func (m *defaultStock) DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductReply, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.DeductRollback(ctx, in, opts...)
}
