// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: stock.proto

package server

import (
	"context"

	"bookNew/service/stock/rpc/internal/logic"
	"bookNew/service/stock/rpc/internal/svc"
	"bookNew/service/stock/rpc/stock"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

// 扣减库存 (Action)
func (s *StockServer) Deduct(ctx context.Context, in *stock.DeductReq) (*stock.DeductReply, error) {
	l := logic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

// 补偿库存 (Compensate) - 如果后续步骤失败，把库存加回来
func (s *StockServer) DeductRollback(ctx context.Context, in *stock.DeductReq) (*stock.DeductReply, error) {
	l := logic.NewDeductRollbackLogic(ctx, s.svcCtx)
	return l.DeductRollback(in)
}
