// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BorrowReply struct {
}

type BorrowReq struct {
	BookId int64 `json:"book_id"`
	UserId int64 `json:"user_id"`
}

type SearchReply struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
	Owner string `json:"owner"` // 新增：显示这本书是谁搜的
}

type SearchReq struct {
	Name string `form:"name"`
}
