// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user_client

import (
	"context"

	"bookNew/service/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdjustPointsReply = user.AdjustPointsReply
	AdjustPointsReq   = user.AdjustPointsReq
	IdReq             = user.IdReq
	UserInfoReply     = user.UserInfoReply

	User interface {
		GetUser(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*UserInfoReply, error)
		// Saga Action: 扣积分
		DecrPoints(ctx context.Context, in *AdjustPointsReq, opts ...grpc.CallOption) (*AdjustPointsReply, error)
		// Saga Compensate: 补偿积分 (把扣掉的加回来)
		DecrPointsRollback(ctx context.Context, in *AdjustPointsReq, opts ...grpc.CallOption) (*AdjustPointsReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// Saga Action: 扣积分
func (m *defaultUser) DecrPoints(ctx context.Context, in *AdjustPointsReq, opts ...grpc.CallOption) (*AdjustPointsReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DecrPoints(ctx, in, opts...)
}

// Saga Compensate: 补偿积分 (把扣掉的加回来)
func (m *defaultUser) DecrPointsRollback(ctx context.Context, in *AdjustPointsReq, opts ...grpc.CallOption) (*AdjustPointsReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DecrPointsRollback(ctx, in, opts...)
}
