// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"bookNew/service/user/rpc/internal/logic"
	"bookNew/service/user/rpc/internal/svc"
	"bookNew/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdReq) (*user.UserInfoReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// Saga Action: 扣积分
func (s *UserServer) DecrPoints(ctx context.Context, in *user.AdjustPointsReq) (*user.AdjustPointsReply, error) {
	l := logic.NewDecrPointsLogic(ctx, s.svcCtx)
	return l.DecrPoints(in)
}

// Saga Compensate: 补偿积分 (把扣掉的加回来)
func (s *UserServer) DecrPointsRollback(ctx context.Context, in *user.AdjustPointsReq) (*user.AdjustPointsReply, error) {
	l := logic.NewDecrPointsRollbackLogic(ctx, s.svcCtx)
	return l.DecrPointsRollback(in)
}
