// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: stock.proto

package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductReq) Reset() {
	*x = DeductReq{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductReq) ProtoMessage() {}

func (x *DeductReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductReq.ProtoReflect.Descriptor instead.
func (*DeductReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *DeductReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *DeductReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductReply) Reset() {
	*x = DeductReply{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductReply) ProtoMessage() {}

func (x *DeductReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductReply.ProtoReflect.Descriptor instead.
func (*DeductReply) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x05stock\":\n" +
	"\tDeductReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\r\n" +
	"\vDeductReply2o\n" +
	"\x05stock\x12.\n" +
	"\x06deduct\x12\x10.stock.DeductReq\x1a\x12.stock.DeductReply\x126\n" +
	"\x0edeductRollback\x12\x10.stock.DeductReq\x1a\x12.stock.DeductReplyB\tZ\a./stockb\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stock_proto_goTypes = []any{
	(*DeductReq)(nil),   // 0: stock.DeductReq
	(*DeductReply)(nil), // 1: stock.DeductReply
}
var file_stock_proto_depIdxs = []int32{
	0, // 0: stock.stock.deduct:input_type -> stock.DeductReq
	0, // 1: stock.stock.deductRollback:input_type -> stock.DeductReq
	1, // 2: stock.stock.deduct:output_type -> stock.DeductReply
	1, // 3: stock.stock.deductRollback:output_type -> stock.DeductReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
