// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stockFieldNames          = builder.RawFieldNames(&Stock{})
	stockRows                = strings.Join(stockFieldNames, ",")
	stockRowsExpectAutoSet   = strings.Join(stringx.Remove(stockFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	stockRowsWithPlaceHolder = strings.Join(stringx.Remove(stockFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoStockIdPrefix     = "cache:go:stock:id:"
	cacheGoStockBookIdPrefix = "cache:go:stock:bookId:"
)

type (
	stockModel interface {
		Insert(ctx context.Context, data *Stock) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Stock, error)
		FindOneByBookId(ctx context.Context, bookId int64) (*Stock, error)
		Update(ctx context.Context, data *Stock) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStockModel struct {
		sqlc.CachedConn
		table string
	}

	Stock struct {
		Id     int64 `db:"id"`
		BookId int64 `db:"book_id"`
		Num    int64 `db:"num"`
	}
)

func newStockModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStockModel {
	return &defaultStockModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`stock`",
	}
}

func (m *defaultStockModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	goStockBookIdKey := fmt.Sprintf("%s%v", cacheGoStockBookIdPrefix, data.BookId)
	goStockIdKey := fmt.Sprintf("%s%v", cacheGoStockIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goStockBookIdKey, goStockIdKey)
	return err
}

func (m *defaultStockModel) FindOne(ctx context.Context, id int64) (*Stock, error) {
	goStockIdKey := fmt.Sprintf("%s%v", cacheGoStockIdPrefix, id)
	var resp Stock
	err := m.QueryRowCtx(ctx, &resp, goStockIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockModel) FindOneByBookId(ctx context.Context, bookId int64) (*Stock, error) {
	goStockBookIdKey := fmt.Sprintf("%s%v", cacheGoStockBookIdPrefix, bookId)
	var resp Stock
	err := m.QueryRowIndexCtx(ctx, &resp, goStockBookIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `book_id` = ? limit 1", stockRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, bookId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockModel) Insert(ctx context.Context, data *Stock) (sql.Result, error) {
	goStockBookIdKey := fmt.Sprintf("%s%v", cacheGoStockBookIdPrefix, data.BookId)
	goStockIdKey := fmt.Sprintf("%s%v", cacheGoStockIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, stockRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BookId, data.Num)
	}, goStockBookIdKey, goStockIdKey)
	return ret, err
}

func (m *defaultStockModel) Update(ctx context.Context, newData *Stock) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	goStockBookIdKey := fmt.Sprintf("%s%v", cacheGoStockBookIdPrefix, data.BookId)
	goStockIdKey := fmt.Sprintf("%s%v", cacheGoStockIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, stockRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.BookId, newData.Num, newData.Id)
	}, goStockBookIdKey, goStockIdKey)
	return err
}

func (m *defaultStockModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoStockIdPrefix, primary)
}

func (m *defaultStockModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStockModel) tableName() string {
	return m.table
}
